- script/cheeseData.js
- script/seed.js
- script/wineData.js
- server/db/models/Wine.js
created seed function, updated wine data and cheese data seed files
> Feature: seed function and data

- public/index.html
updated title to grace monger from fs-template-app
> update title in index.html

- server/api/cheese.spec.js
- server/api/index.js
- server/db/index.js
I added tests for my get route for all cheeses
> made tests for get all cheese route

- client/components/SingleWine.js
> Fixed tasing notes

- client/components/AllWines.js
- client/components/SingleWine.js
- client/store/singleWine.js
- server/api/wines.spec.js
Added quantity incrementor in single wine view and specs for backend routes for all wines view.
> Single wine view

- server/db/index.js
Added a one-to-one relationship for cheese and wine tables. So cheese table has wine id and wine table has cheese id.
> added one to one relationship to wine and cheese

- script/seed.js
- script/wineData.js
- server/api/cheeses.js
I made a get route to fetch a single cheese from the backend based on id but I commented out the the include
> Get route for single cheese

- client/components/AllCheese.js
- client/store/cheeses.js
- client/store/index.js
> Front end for single cheese

- client/Routes.js
- client/components/SingleCheese.js
- client/store/index.js
- client/store/singleCheese.js
Added a component to display single cheese and created a reducer to handle single cheese state
> Front end single cheese

- client/components/CreateWine.js
- client/store/wines.js
- server/api/wines.js
Still working on it ! Just wanted to push some of my changes so far.
> Working on create wine functionality

- client/components/SingleCheese.js
Added user id to my single cheese component
> added userid to single cheese

- client/Routes.js
Added single cheese route to routes.js
> added single cheese to routes.js

- client/components/SingleCheese.js
- client/components/SingleWine.js
- client/store/order.js
- server/api/order.js
- server/db/index.js
- server/db/models/Order_Cheese.js
Made post routes to add a cheese and wine to a specific orderId and also created a order_cheese model. Also set up store  to handle add a new cheese and wine
> added post routes for cheese and wine and order_cheese model

- client/components/Order.js
can also click from cart to go into product single view
> Feature: updated order component to display wines and cheeses in cart

- public/style.css
Made add to cart button a little cuter
> Styling addtocart button

- client/components/AllCheese.js
- client/store/order.js
- server/api/order.js
I got rid of some console logs for my post routes in order.js so my code is cleaner
> cleaned up code for post route in order.js

- client/components/AllCheese.js
- client/components/CreateCheese.js
- client/store/cheeses.js
- server/api/cheeses.js
Made a add new cheese form component, post route in backend, and made thunk in store
> add new cheese post route, store, and component

- client/components/AllCheese.js
- client/components/CreateCheese.js
- client/store/cheeses.js
- server/api/cheeses.js
Vertical slice for delete cheese: delete route, delete thunk, and delete button in allCheeseComponent
> Delete cheese 

- client/components/AllCheese.js
- client/components/AllWines.js
- client/components/SingleCheese.js
- client/components/SingleWine.js
We need to render specific forms or buttons when a user is both logged in and an admin because  admins have specific admin rights. 
This PR should display the delete button and add new product form on all products view when a user is logged in and is an admin. This PR should also display the edit product form under single product page only when a user is logged in and an admin. 
Login in as a regular user (aka me or Alison) NONE of the forms or delete button should show up.
Login in as an admin (aka Jackie) the forms and delete button should show up .
> Trying to find admin

- public/style.css
- server/api/order.js
- server/db/index.js
with a weird bug ... will discuss tomorrow but moving on to deleting ind items....
> clear cart works?

- client/components/AllCheese.js
- client/components/AllWines.js
- public/style.css
I changed remove cheese and remove wine button to red 
Shows red button in all products views 
Go to all products view while logged in as admin. Red remove button should show up for each item
> changed delete button and added color

- client/Routes.js
- client/components/AllCheese.js
- client/components/AllWines.js
- client/components/Order.js
- client/store/order.js
- script/userData.js
- server/api/gateKeepingMiddleware.js
- server/api/users.js
- server/auth/index.js
- server/db/models/User.js
Added an isAdmin field to user model and made sure sign up post route doesnt allow users to add themselves as admin. Also refactored isAdmin components in front end to show only if isAdmin field is set to true
> added more security for admin

- .env
- client/components/EditCheese.js
- client/components/EditWine.js
- client/components/Order.js
- client/store/order.js
- server/api/order.js
Fixed quantity and delete in cart. And fixed guest empty cart view
> Quantity in cart

- client/components/Order.js
- server/db/models/Order_Cheese.js
- server/db/models/Order_Wine.js
> added subtotal to cart view and price for single item

- client/components/Order.js
- public/style.css
styled button in cart and added hover
> styled buttons in cart

- client/components/CreateWine.js
- client/store/wines.js
- server/api/wines.js
- server/db/models/Wine.js
fixed create wine bug in console
> fixed bug in create wine

- client/components/LoginForm.js
- client/components/SignUpForm.js
- public/style.css
pr for login and signup button
> styled login and signup button

- client/components/CreateCheese.js
- client/components/CreateWine.js
- client/components/EditCheese.js
- client/components/EditWine.js
- public/style.css
> styled submit buttons
